const albums = [
    "The College Dropout",
    "Late Registration",
    "Graduation",
    "808s & Heartbreak",
    "My Beautiful Dark Twisted Fantasy",
    "Yeezus",
    "The Life of Pablo",
    "Ye",
    "Jesus Is King",
    "Certified Lover Boy",
    "Scorpion",
    "Views",
    "More Life",
    "Nothing Was the Same",
    "Take Care",
    "Thank Me Later",
    "Revenge of the Dreamers III",
    "KOD",
    "4 Your Eyez Only",
    "2014 Forest Hills Drive",
    "The Off-Season",
    "Music to Be Murdered By",
    "Kamikaze",
    "Revival",
    "The Marshall Mathers LP 2",
    "Recovery",
    "Relapse",
    "Encore",
    "The Eminem Show",
    "The Slim Shady LP",
    "Testing",
    "Long. Live. ASAP",
    "At. Long. Last. ASAP",
    "Kendrick Lamar EP",
    "Section.80",
    "Good Kid, M.A.A.D City",
    "To Pimp a Butterfly",
    "untitled unmastered.",
    "DAMN.",
    "The Heist",
    "This Unruly Mess I've Made",
    "The Language of My World",
    "How I Got Over",
    "The Roots Come Alive",
    "Under Pressure",
    "YSIV",
    "Bobby Tarantino II",
    "Bobby Tarantino",
    "Confessions of a Dangerous Mind",
    "Supermarket",
    "I Decided.",
    "Dark Sky Paradise",
    "Hall of Fame",
    "Finally Famous",
];

export default albums;
